// react/user-management/src/components/home.js
import React, { useEffect, useState } from 'react'
import { Link} from 'react-router-dom';
import Modal from 'react-bootstrap/Modal';

const Home = () => {
    const [data, setData] = useState([]);
    const [editing, setEditing] = useState(null);
    const [showModal, setShowModal] = useState(false);
    const [addUser, setAddUser] = useState(false);
    const handleAddUser=()=>{
        setAddUser(true);
        setShowModal(true);
        // navigate('../register');
    }
    const handleDelete=(user)=>{
        const existingData=JSON.parse(localStorage.getItem('data'));
        const updatedArray = existingData.filter(obj => obj.username !== user);
        localStorage.setItem("data", JSON.stringify(updatedArray));
        setData(updatedArray);
    }
    const handleEdit=(user)=>{
        setAddUser(false);
        setEditing(user);
        setShowModal(true);
    }
    const handleCloseModal = () => {
        setEditing(null);
        setShowModal(false);
    };
    function isValidEmail(email) {
        return /\S+@\S+\.\S+/.test(email);
    }
    const handleSave = () => {
        if(addUser){
            //add user true
            if(!editing || !editing.firstname || !editing.username || !editing.gender || !editing.password){
                alert('Please fill in all required fields!');
            }
            else if(!editing.email || !isValidEmail(editing.email)){
                alert('Please enter valid email');
            }
            else {
                const index = data.findIndex((item) => (item.email === editing.email || item.username===editing.username));
                if(index!==-1){
                    alert('Already registered! Try Log in')
                }
                else {
                    data.push(editing);
                    localStorage.setItem("data", JSON.stringify(data));
                    handleCloseModal();
                } 
            }
        }
        else {
            const updatedData = [...data];
            const index = data.findIndex((item) => item.email === editing.email);
            updatedData[index] = editing;
            setData(updatedData);
            localStorage.setItem("data", JSON.stringify(updatedData));
            handleCloseModal(); 
        }
    }
    useEffect(()=>{
        const items = JSON.parse(localStorage.getItem('data'));
            if(items){
                setData(items);           
            }  
    },[]);

  return (
    <div>
      <h1 className='text-center'>User Details</h1>
      <button type='button' className='btn btn-primary' onClick={handleAddUser}>Add User</button>
      <table className='table'>
        <thead>
            <tr>
                <th scope='col'>First Name</th>
                <th scope='col'>Last Name</th>
                <th scope='col'>UserName</th>
                <th scope='col'>Email</th>
                <th scope='col'>Password</th>
                <th scope='col'>Gender</th>
                <th scope='col'>Action</th>
            </tr>
        </thead>
        <tbody>
            {data.map((item)=>{
                return(
                    <tr key={item.username}>
                    <td>{item.firstname}</td>
                    <td>{item.lastname}</td>
                    <td>{item.username}</td>
                    <td>{item.email}</td>
                    <td>{item.password}</td>
                    <td>{item.gender}</td>
                    <td>
                        <button type='button' className='btn btn-primary' onClick={()=>handleEdit(item)}>Edit</button>
                        <button type='button' className='btn btn-secondary ms-3' onClick={() => handleDelete(item.username)}>Delete</button>
                    </td>
                    </tr>
                );
            })}

        </tbody>
      </table>
      <Link to='/' className='btn btn-primary'>Logout</Link>
        <Modal show={showModal} onHide={handleCloseModal}>
            <Modal.Header closeButton>
            <Modal.Title>
                {addUser?'Add':'Edit'} User
            </Modal.Title>
            </Modal.Header>
            <Modal.Body>
                <div className='form-group'>
                <label htmlFor='firstname' className='form-label'><b>First Name*</b></label>
                <input type='text' className='form-control' name='firstname' 
                value={editing?.firstname || ''}
                onChange={(e) =>
                    setEditing({ ...editing, firstname: e.target.value })
                    }
                />
            </div>
            <div className='form-group mt-2'>
                <label htmlFor='lastname' className='form-label'><b>Last Name</b></label>
                <input type='text' className='form-control' name='lastname' 
                value={editing?.lastname || ''}
                onChange={(e) =>
                    setEditing({ ...editing, lastname: e.target.value })
                    }
                />
            </div>
            <div className='form-group mt-2'>
                <label htmlFor='username' className='form-label'><b>Username*</b></label>
                <input type='text' className='form-control' name='username' 
                value={editing?.username || ''}
                onChange={(e) =>
                    setEditing({ ...editing, username: e.target.value })
                    }
                />
            </div>
            <div className='form-group mt-2'>
                <label htmlFor='gender' className='form-label'><b>Gender*</b></label>
                <div className="form-check form-check-inline mx-4">
                    <input className="form-check-input" type="radio" name="gender" value="male"
                    checked={editing?.gender === 'male'} 
                    onChange={(e) =>
                    setEditing({ ...editing, gender: 'male' })
                    }
                />
                    <label className="form-check-label" htmlFor="male">Male</label>
                </div>
                <div className="form-check form-check-inline">
                    <input className="form-check-input" type="radio" name="gender" value="female" 
                    checked={editing?.gender === 'female'}
                    onChange={(e) =>
                    setEditing({ ...editing, gender: 'female' })
                    }
                />
                    <label className="form-check-label" htmlFor="female">Female</label>
                </div>
            </div>
            {addUser?<div className='form-group mt-2'>
                <label htmlFor='email' className='form-label'><b>Email*</b></label>
                <input type='email' className='form-control' name='email' 
                value={editing?.email || ''}
                onChange={(e) =>
                    setEditing({ ...editing, email: e.target.value })
                    }
                />
            </div>
            :''}
            <div className='form-group mt-2'>
                <label htmlFor='password' className='form-label'><b>Password*</b></label>
                <input type='password' className='form-control' name='password' 
                value={editing?.password || ''}
                onChange={(e) =>
                    setEditing({ ...editing, password: e.target.value })
                    }
                />
            </div>
            </Modal.Body>
            <Modal.Footer>
            <button className="btn btn-secondary" onClick={handleCloseModal}>
                Close
            </button>
            <button className="btn btn-primary" onClick={handleSave}>
                Save Changes
            </button>
            </Modal.Footer>
        </Modal>

    </div>
  )}

export default Home;

// angular/user-management/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from 'src/app/auth.service';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit{
  submit=false;
  userData:any[]=[];
  modalText='Edit';
  form=this.fb.group({
    firstname: ['', Validators.required],
    lastname: ['', Validators.required],
      username: ['', [Validators.required, Validators.maxLength(15)]],
      gender: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [
        Validators.required,
        Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/), 
      ]],
  })
  get user(){
    return this.form.controls
  }
  constructor(private fb:FormBuilder, private auth:AuthService){
  };

  ngOnInit(): void {
    const data=localStorage.getItem('data');
    if(data!==null){
      this.userData=JSON.parse(data);
    }
  }
  logout(){
    this.auth.logout();
  }
  handleDelete(index: any){
    this.userData.splice(index,1);
    localStorage.setItem('data', JSON.stringify(this.userData));
  }
  openModal(index:any){
    const modalDiv=document.getElementById('exampleModal');
    if(modalDiv!=null){
      modalDiv.style.display='block';
    }
    if(index!==-1){
      this.modalText='Edit';
      this.user['firstname'].setValue(this.userData[index].firstname);
      this.user['lastname'].setValue(this.userData[index].lastname);
      this.user['username'].setValue(this.userData[index].username);
      this.user['email'].setValue(this.userData[index].email);
      this.user['password'].setValue(this.userData[index].password);
      this.user['gender'].setValue(this.userData[index].gender);  
      console.log(this.userData[index])
    }
    else{
      this.modalText='Add';
      this.user['firstname'].setValue('');
      this.user['lastname'].setValue('');
      this.user['username'].setValue('');
      this.user['email'].setValue('');
      this.user['password'].setValue('');
      this.user['gender'].setValue('');
    }
  }
  closeModal(){
    const modalDiv=document.getElementById('exampleModal');
    if(modalDiv!=null){
      modalDiv.style.display='none';
    }
  }
  saveChanges(){
    this.submit=true;
    if(this.form.invalid) return;
    const index=this.userData.findIndex((user)=>user.username===this.user['username'].value);
    if(index!==-1){
      this.userData[index]={
        firstname: this.user['firstname'].value,
        lastname: this.user['lastname'].value,
        username: this.user['username'].value,
        email: this.user['email'].value,
        password: this.user['password'].value,
        gender: this.user['gender'].value,
      };
    }
    else{
      const newUser={
        firstname: this.user['firstname'].value,
        lastname: this.user['lastname'].value,
        username: this.user['username'].value,
        email: this.user['email'].value,
        password: this.user['password'].value,
        gender: this.user['gender'].value,
      }
      this.userData.push(newUser);
    }
    localStorage.setItem('data', JSON.stringify(this.userData));
    this.closeModal();
  }
}

<h1>User Details</h1>
<button class="btn btn-primary" (click)="openModal(-1)">Add User</button>
<table class='table'>
    <thead>
        <tr>
            <th scope='col'>First Name</th>
            <th scope='col'>Last Name</th>
            <th scope='col'>UserName</th>
            <th scope='col'>Email</th>
            <th scope='col'>Password</th>
            <th scope='col'>Gender</th>
            <th scope='col'>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let item of userData index as i">
            <td>{{item.firstname | namePrefix:item.gender}}</td>
            <td>{{item.lastname}}</td>
            <td>{{item.username}}</td>
            <td>{{item.email}}</td>
            <td>{{item.password}}</td>
            <td>{{item.gender}}</td>
            <td>
                <button type='button' class='btn btn-primary' (click)="openModal(i)">Edit</button>
                <button type='button' class='btn btn-secondary ms-3' (click)="handleDelete(i)">Delete</button>
            </td>
            </tr>
    </tbody>
  </table>
<button class="btn btn-primary" (click)="logout()">Logout</button>
<div class="modal" id="exampleModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <form class="modal-content" [formGroup]="form" (ngSubmit)="saveChanges()">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{{modalText}} User Details</h5>
          <button type="button" class="close" (click)="closeModal()">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-6">
                    <div class="form-group mt-3">
                      <label for='firstname' class='form-label'><b>First Name</b></label>
                      <input type='text' class='form-control' name='firstname' formControlName="firstname"/>
                      <span *ngIf="submit && user?.['firstname']?.errors"><small class="text-danger">Firstname is Required</small></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group mt-3">
                      <label for='lastname' class='form-label'><b>Last Name</b></label>
                      <input type='text' class='form-control' name='lastname' formControlName="lastname"/>
                      <span *ngIf="submit && user?.['lastname']?.errors"><small class="text-danger">Lastname is Required</small></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <div class="form-group mt-3">
                      <label for='username' class='form-label'><b>Username</b></label>
                      <input type='text' class='form-control' name='username' formControlName="username"/>
                      <span *ngIf="submit && user?.['username']?.errors"><small class="text-danger">Username is Required</small></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group mt-3">
                      <label for='email' class='form-label'><b>Email</b></label>
                      <input type='email' class='form-control' name='email' formControlName="email"/>
                      <span *ngIf="submit && user?.['email']?.errors?.['required']"><small class="text-danger">Email is Required</small></span>
                      <span *ngIf="submit && user?.['email']?.errors?.['email']"><small class="text-danger">Email is not valid</small></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <div class="form-group mt-3">
                      <label for='password' class='form-label'><b>Password</b></label>
                      <input type='password' class='form-control' name='password' formControlName="password"/>
                      <span *ngIf="submit && user?.['password']?.errors?.['required']"><small class="text-danger">Password is Required</small></span>
                      <span *ngIf="submit && user?.['password']?.errors?.['pattern']"><small class="text-danger">Must contain 1 uppercase, 1 lowercase, 1 digit, 1 special character</small></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group mt-3">
                        <div>
                            <label for='gender' class='form-label'><b>Gender</b></label>
                        </div>
                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" name="gender" id="male" value="male" formControlName="gender">
                        <label for="male" class="form-check-label">Male</label>
                      </div>
                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" name="gender" id="female" value="female" formControlName="gender">
                        <label for="female" class="form-check-label">Female</label>
                      </div>
                    </div>
                    <span *ngIf="submit && user?.['gender']?.errors"><small class="text-danger">Gender is Required</small></span>
                </div>
            </div>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="closeModal()">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </form>
    </div>
</div>
