// angular/user-management/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import {FormBuilder, NgForm} from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/auth.service';
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  loginForm = this.fb.group({
    username: [''],
    password: ['']
  })
  success=true;
  constructor(private fb:FormBuilder, private router: Router, private auth:AuthService){
    // localStorage.removeItem('token');
    if(this.auth.isLoggedIn()){
      this.router.navigate(['../home']);
    }
  }
  onSubmit(){
    console.log(this.loginForm.value);
    if(this.auth.login(this.loginForm.value)){
      this.router.navigate(['../home']);    
    }
    else{
      this.success=false;
    }
    
    
    // this.router.navigate(['../home']);
  //   const data=localStorage.getItem('data');
  //   if(data!==null){
  //   const items = JSON.parse(data);
  //   items.forEach((element: { username: any; password: any; }) => {
  //     if(element.username===this.loginForm.value.username && element.password === this.loginForm.value.password){
  //         this.router.navigate(['../home']);
  //     }
  //     else{
  //       // this.auth=false;
  //     }
  //   }); 
  // } else{
  //   // this.auth=false;
  //   }
  }
}

<h1 class="display">Login Component</h1>
<form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
<div class="form-group my-3">
    <label for="username">Username</label>
    <input type="text" id="username" name="username" class="form-control" formControlName="username">
</div>
<div class="form-group my-3">
    <label for="password">Password</label>
    <input type="password" id="password" name="password" class="form-control" formControlName="password">
</div>
<div *ngIf="success===false" class='text-danger my-3'>Wrong Details! try again</div>

<button class="btn btn-primary" type="submit">Login</button>
<button class="btn btn-primary mx-3" routerLink="../register">Register</button>
</form>

// react/user-management/src/components/login.js
import {useFormik} from 'formik';
import * as yup from 'yup';
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';
const Login = () => {
    const navigate = useNavigate();
    const [auth, setAuth] = useState(true)
    const formik = useFormik({
        initialValues:{
            username: '',
            password: '',
        },
        validationSchema: yup.object({
            username: yup.string()
            .required('Username is required')
            .max(15, 'Must be 15 characters or less'),
            password: yup.string()
            .required('Password is required'),
        }),
        onSubmit: values => {
            const items = JSON.parse(localStorage.getItem('data'));
            
            items.forEach(element => {
                if(element.username===values.username && element.password === values.password){
                    navigate('/home');
                }
                else{
                    setAuth(false);
                }
            }); 
        },
    });

  return (
    <div>
        <h1 className='text-center my-4'>Welcome to Login Page</h1>
        <form onSubmit={formik.handleSubmit}>
            <div className='form-group'>
                <label htmlFor='username' className='form-label'>Username</label>
                <input type='text' className='form-control' name='username' onChange={formik.handleChange} value={formik.values.username}/>
                {formik.errors.username ? <div className='invalid-feedback d-block'>{formik.errors.username}</div> : null}

            </div>
            <div className='form-group my-2'>
                <label htmlFor='password' className='form-label'>Password</label>
                <input type='password' className='form-control' name='password' onChange={formik.handleChange} value={formik.values.password}/>
                {formik.errors.password ? <div className='invalid-feedback d-block'>{formik.errors.password}</div> : null}
            </div>
            <button type="submit" className="btn btn-primary">Submit</button> 
        </form>
        {auth?'':<div className='text-danger'>Wrong Details! try again</div>}
    </div>
  )
}

export default Login;
