// angular/user-management/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import { Router } from '@angular/router';
@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  submitted:boolean=false;
  registerForm:FormGroup;
  
  constructor(private fb:FormBuilder, private router: Router){
    this.registerForm = this.fb.group({
      firstname: ['', Validators.required],
      lastname: ['', Validators.required],
      username: ['', [Validators.required, Validators.maxLength(15)]],
      gender: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [
        Validators.required,
        Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/),
        Validators.minLength(8), 
      ]],
      confirm:['', [Validators.required]]
    }
    ,{
      validators:this.passwordMatch('password', 'confirm')
    }
    );
  }
  
  get user(){
    return this.registerForm.controls
  }
  passwordMatch(password:string, confirm:string){
    return(formGroup:FormGroup)=>{
      const first=formGroup.controls[password];
      const second=formGroup.controls[confirm];
      if(first.errors && !second.errors?.['passwordMatch']){
        return;
      }
      if(first.value!==second.value){
        second.setErrors({passwordMatch:true});
      }
      else{
        second.setErrors(null);
      }
    }
  }
  onSubmit(){
    this.submitted=true;
    if(this.registerForm.invalid) return;
    let existingData=[]
    let storedData=localStorage.getItem('data');
    if(storedData){
      existingData=JSON.parse(storedData);
    }
    const userExists = existingData.some((user: { username: string | null | undefined; }) => user.username === this.registerForm.value.username);
    const emailExists = existingData.some((user: { email: string | null | undefined; }) => user.email === this.registerForm.value.email);
    if(userExists){
      alert('Username already exists!');
    }
    else if(emailExists){
      alert('Email already exists!');
    }
    else{
      localStorage.setItem("data", JSON.stringify([...existingData,this.registerForm.value]));
      this.router.navigate(['../login']);
    }
  }  
}

<h1 class="display">Register Component</h1>
<form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
<div class="form-group my-3">
    <label for="firstname">Firstname</label>
    <input type="text" name="firstname" class="form-control" formControlName="firstname" >
    <span class="text-danger" *ngIf="submitted && user?.['firstname']?.errors"><small>*Firstname is required</small></span>
</div>
<div class="form-group my-3">
    <label for="lastname">Lastname</label>
    <input type="text" name="lastname" class="form-control" formControlName="lastname">
    <span class="text-danger" *ngIf="submitted && user?.['lastname']?.errors"><small>*Lastname is required</small></span>
</div>
<div class="form-group my-3">
    <label for="username">Username</label>
    <input type="text" name="username" class="form-control" formControlName="username">
    <span class="text-danger" *ngIf="submitted && user?.['username']?.errors"><small>*Username is required</small></span>
</div>
<div class="form-group my-3">
    <label for="gender">Gender</label>
    <div class="form-check form-check-inline mx-4">
        <input type="radio" class="form-check-input" id="male" value="male" formControlName="gender">
        <label for="male">Male</label>
    </div>
    <div class="form-check form-check-inline">
        <input type="radio" class="form-check-input" id="female" value="female" formControlName="gender">
        <label for="female">Female</label>
    </div>
    <div class="text-danger" *ngIf="submitted && user?.['gender']?.errors"><small>*Gender is required</small></div>
</div>
<div class="form-group my-3">
    <label for="email">Email</label>
    <input type="email" name="email" class="form-control" formControlName="email">
    <span *ngIf="submitted && user?.['email']?.errors">
        <span *ngIf="user?.['email']?.errors?.['required']"><small class="text-danger">*Email is required</small></span>
        <span *ngIf="user?.['email']?.errors?.['email']"><small class="text-danger">Email is not valid</small></span>
    </span>
</div>
<div class="form-group my-3">
    <label for="password">Password</label>
    <input type="password" name="password" class="form-control" formControlName="password" >
    <span *ngIf="submitted && user?.['password']?.errors">
        <span *ngIf="user?.['password']?.errors?.['required']"><small class="text-danger">*Password is required</small></span>
        <span *ngIf="user?.['password']?.errors?.['pattern']"><small class="text-danger">Must contain 1 uppercase, 1 lowercase, 1 digit, 1 special character</small></span>
        <span *ngIf="user?.['password']?.errors?.['minlength']"><small class="text-danger">Minimum 8 character length</small></span>
    </span>
</div>
<div class="form-group my-3">
    <label for="confirm">Confirm Password</label>
    <input type="password" name="confirm" class="form-control" formControlName="confirm" >
    <span *ngIf="submitted && user?.['confirm']?.errors">
        <span *ngIf="user?.['confirm']?.errors?.['required']"><small class="text-danger">*Confirm Password is required</small></span>
        <span *ngIf="user?.['confirm']?.errors?.['passwordMatch']"><small class="text-danger">Confirm password does not match</small></span>
    </span>
</div>
<button class="btn btn-primary" routerLink="../login">Login</button>
<button class="btn btn-primary mx-3" type="submit">Register</button>
</form>

// react/user-management/src/components/register.js
import {useFormik} from 'formik';
import {useNavigate} from 'react-router-dom';
import * as yup from 'yup';
const Register = () => {
    const navigate = useNavigate();
    const formik = useFormik({
        initialValues:{
            firstname: '',
            lastname: '',
            username: '',
            gender: '',
            email: '',
            password: '',
            confirmPassword: '',
        },
        validationSchema: yup.object({
            firstname: yup.string()
            .required('First Name is required')
            .max(15, 'Must be 15 characters or less'),
            username: yup.string()
            .required('Username is required')
            .max(15, 'Must be 15 characters or less'),
            gender: yup.string()
            .required('Required'),
            email: yup.string()
            .required('Email is required')
            .email('Invalid email'),
            password: yup.string()
            // .min(8, '8 characters minimum')
            // .matches(/[0-9]/, "Must contain a digit")
            // .matches(/[a-z]/, "Must contain a lowercase")
            // .matches(/[A-Z]/, "Must contain a uppercase")
            // .matches(/[^\w]/, 'Must containe a special character')
            .required('Password is required'),
            confirmPassword: yup.string()
            .required("Please re-type your password")
            .oneOf([yup.ref("password")], "Passwords does not match"),
        }),
        onSubmit: values => {
            const storedData = localStorage.getItem('data');
            let existingData = [];
            if(storedData){
                existingData=JSON.parse(storedData);
            }
            const userExists = existingData.some(user => user.username === values.username);
            const emailExists = existingData.some(user => user.email === values.email);
            if(userExists){
                alert('Username already exists!');
            }
            else if(emailExists){
                alert('Email already exists!');
            }
            else{
                localStorage.setItem("data", JSON.stringify([...existingData,values]));
                navigate('../');
            }     
        },
    });
  return (
    <div>
        <h1 className='text-center my-4'>Registeration Form</h1>
        <form onSubmit={formik.handleSubmit}>
            <div className='form-group'>
                <label htmlFor='firstname' className='form-label'>Firstname</label>
                <input type='text' className='form-control' name='firstname' onChange={formik.handleChange} value={formik.values.firstname}/>
                {formik.errors.firstname ? <div className='invalid-feedback d-block'>{formik.errors.firstname}</div> : null}
            </div>
            <div className='form-group my-2'>
                <label htmlFor='lastname' className='form-label'>Lastname</label>
                <input type='text' className='form-control' name='lastname' onChange={formik.handleChange} value={formik.values.lastname}/>
                {formik.errors.lastname ? <div className='invalid-feedback d-block'>{formik.errors.lastname}</div> : null}
            </div>
            <div className='form-group my-2'>
                <label htmlFor='username' className='form-label'>Username</label>
                <input type='text' className='form-control' name='username' onChange={formik.handleChange} value={formik.values.username}/>
                {formik.errors.username ? <div className='invalid-feedback d-block'>{formik.errors.username}</div> : null}
            </div>
            <div className='form-group mt-3'>
                <label htmlFor='gender' className='form-label'>Gender</label>
                <div className="form-check form-check-inline mx-4">
                    <input className="form-check-input" type="radio" name="gender" value="male" onChange={formik.handleChange}/>
                    <label className="form-check-label" htmlFor="male">Male</label>
                </div>
                <div className="form-check form-check-inline">
                    <input className="form-check-input" type="radio" name="gender" value="female" onChange={formik.handleChange}/>
                    <label className="form-check-label" htmlFor="female">Female</label>
                </div>
                {formik.errors.gender ? <div className='invalid-feedback d-block'>{formik.errors.gender}</div> : null}
            </div>
            <div className='form-group my-2'>
                <label htmlFor='email' className='form-label'>Email</label>
                <input type='email' className='form-control' name='email' onChange={formik.handleChange} value={formik.values.email}/>
                {formik.errors.email ? <div className='invalid-feedback d-block'>{formik.errors.email}</div> : null}
            </div>
            <div className='form-group my-2'>
                <label htmlFor='password' className='form-label'>Password</label>
                <input type='password' className='form-control' name='password' onChange={formik.handleChange} value={formik.values.password}/>
                {formik.errors.password ? <div className='invalid-feedback d-block'>{formik.errors.password}</div> : null}
            </div>
            <div className='form-group my-2'>
                <label htmlFor='confirmPassword' className='form-label'>Confirm Password</label>
                <input type='password' className='form-control' name='confirmPassword' onChange={formik.handleChange} value={formik.values.confirmPassword}/>
                {formik.errors.confirmPassword ? <div className='invalid-feedback d-block'>{formik.errors.confirmPassword}</div> : null}
            </div>
            <button type="submit" className="btn btn-primary my-2">Submit</button> 
        </form>
    </div>
  )
}

export default Register;
